# Generated by Django 5.2 on 2025-04-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "사람", "verbose_name_plural": "사람"},
        ),
    ]
