sonar.projectKey=sweepseries_Sweepseries
sonar.organization=sweepseries
sonar.projectName=Sweepseries
sonar.projectVersion=1.0
sonar.sources=catchb,catchb-admin,sweepserver
sonar.python.version=3.13
sonar.exclusions=\
**/migrations/*,\
**/__init__.py,\
**/wsgi.py,\
**/asgi.py,\
**/manage.py
sonar.coverage.exclusions=\
catchb/src/app/*,\
**/migrations/*,\
**/*.test.tsx,\
**/*.test.ts,\
**/context.ts,\
**/index.ts,\
**/styles.ts,\
**/types.ts,\
**/setup.tsx,\
**/*.d.ts,\
**/*.config.js,\
**/__init__.py,\
**/wsgi.py,\
**/asgi.py,\
**/manage.py
sonar.javascript.lcov.reportPaths=catchb/coverage.lcov,catchb-admin/coverage.lcov
sonar.python.coverage.reportPaths=sweepserver/coverage.xml
