# Generated by Django 5.2 on 2025-06-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "커뮤니티 게시판",
                "verbose_name_plural": "커뮤니티 게시판",
                "db_table": "community_forum",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                ("background_color", models.CharField(default="#F0F0F0", max_length=7)),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="forum.forum",
                    ),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 태그",
                "verbose_name_plural": "커뮤니티 태그",
                "db_table": "community_tag",
                "ordering": ["id"],
                "unique_together": {("forum", "name")},
            },
        ),
    ]
