# Generated by Django 5.2 on 2025-05-27 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "약관",
                "verbose_name_plural": "약관",
                "db_table": "terms",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TermsAndConditionsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True)),
                ("update_summary", models.TextField()),
                (
                    "terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="terms.termsandconditions",
                    ),
                ),
            ],
            options={
                "verbose_name": "약관 이력",
                "verbose_name_plural": "약관 이력",
                "db_table": "terms_history",
            },
        ),
    ]
