# Generated by Django 5.2 on 2025-04-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termsandconditions",
            options={
                "ordering": ["order"],
                "verbose_name": "약관",
                "verbose_name_plural": "약관",
            },
        ),
        migrations.AddField(
            model_name="termsandconditions",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
