# Generated by Django 5.2.1 on 2025-06-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#000000", max_length=7)),
            ],
            options={
                "verbose_name": "FAQ 카테고리",
                "verbose_name_plural": "FAQ 카테고리",
                "db_table": "faq_category",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="faq.faqcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "자주 묻는 질문",
                "verbose_name_plural": "자주 묻는 질문",
                "db_table": "faq",
                "ordering": ["is_active", "id"],
            },
        ),
    ]
