# Generated by Django 5.2 on 2025-05-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.IntegerField(
                        choices=[
                            (0, "미입력"),
                            (1, "기록 삭제"),
                            (2, "개인정보 유출"),
                            (3, "비활동"),
                            (4, "불편함"),
                            (5, "다른 서비스 이용"),
                            (6, "오류"),
                            (7, "기타"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "reason_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("was_coach", models.BooleanField(default=False)),
                ("was_owner", models.BooleanField(default=False)),
                ("was_naver", models.BooleanField(default=False)),
                ("was_kakao", models.BooleanField(default=False)),
                ("was_member_for", models.IntegerField(default=0)),
                (
                    "register_route",
                    models.IntegerField(
                        choices=[(0, "캐치비"), (1, "네이버"), (2, "카카오")], default=0
                    ),
                ),
                ("birth_year", models.PositiveSmallIntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("U", "미입력"),
                            ("M", "남성"),
                            ("F", "여성"),
                            ("O", "기타"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "회원 탈퇴",
                "verbose_name_plural": "회원 탈퇴",
                "db_table": "withdrawal",
            },
        ),
    ]
