# Generated by Django 5.2 on 2025-06-10 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_name", models.CharField(max_length=255)),
                ("profile_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("profile_image", models.URLField(null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 프로필",
                "verbose_name_plural": "커뮤니티 프로필",
                "db_table": "community_profile",
            },
        ),
    ]
