# Generated by Django 5.2 on 2025-05-14 06:24

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("category", models.IntegerField(choices=[(0, "기타")], default=0)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "대기"), (2, "진행중"), (3, "완료")], default=1
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "1:1 문의 스레드",
                "verbose_name_plural": "1:1 문의 스레드",
                "db_table": "inquiry_thread",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.IntegerField(
                        choices=[(1, "사용자"), (2, "관리자"), (3, "시스템")], default=1
                    ),
                ),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="inquiry.inquirythread",
                    ),
                ),
            ],
            options={
                "verbose_name": "1:1 문의 메시지",
                "verbose_name_plural": "1:1 문의 메시지",
                "db_table": "inquiry_message",
                "ordering": ["created_at"],
            },
        ),
    ]
