# Generated by Django 5.2.1 on 2025-06-07 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InquiryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#000000", max_length=7)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "1:1 문의 카테고리",
                "verbose_name_plural": "1:1 문의 카테고리",
                "db_table": "inquiry_category",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="InquiryStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#000000", max_length=7)),
            ],
            options={
                "verbose_name": "1:1 문의 상태",
                "verbose_name_plural": "1:1 문의 상태",
                "db_table": "inquiry_status",
            },
        ),
        migrations.CreateModel(
            name="InquiryThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiry_threads",
                        to="inquiry.inquirycategory",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiry_threads",
                        to="inquiry.inquirystatus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "1:1 문의 스레드",
                "verbose_name_plural": "1:1 문의 스레드",
                "db_table": "inquiry_thread",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.IntegerField(
                        choices=[(1, "사용자"), (2, "관리자"), (3, "시스템")], default=1
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiry_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="inquiry.inquirythread",
                    ),
                ),
            ],
            options={
                "verbose_name": "1:1 문의 메시지",
                "verbose_name_plural": "1:1 문의 메시지",
                "db_table": "inquiry_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryAdminNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notes",
                        to="inquiry.inquirythread",
                    ),
                ),
            ],
            options={
                "verbose_name": "1:1 문의 관리자 노트",
                "verbose_name_plural": "1:1 문의 관리자 노트",
                "db_table": "inquiry_admin_note",
                "ordering": ["created_at"],
            },
        ),
    ]
