# Generated by Django 5.2 on 2025-05-14 05:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(choices=[(0, "기타")], default=0, max_length=50),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[(1, "대기"), (2, "진행중"), (3, "완료")],
                        default=1,
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "1:1 문의",
                "verbose_name_plural": "1:1 문의",
                "db_table": "inquiry",
                "ordering": ["-created_at"],
            },
        ),
    ]
