# Generated by Django 5.2 on 2025-06-11 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community_profile", "0001_initial"),
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySequence",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("last", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "일일 시퀀스",
                "verbose_name_plural": "일일 시퀀스",
                "db_table": "daily_sequence",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=40)),
                ("content", models.TextField()),
                ("num_views", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="community_profile.communityprofile",
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="forum.forum",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="forum.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 게시글",
                "verbose_name_plural": "커뮤니티 게시글",
                "db_table": "community_post",
                "ordering": ["-created_at"],
                "unique_together": {("forum", "author", "title")},
            },
        ),
        migrations.CreateModel(
            name="PostImageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="post.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "커뮤니티 게시글 이미지",
                "verbose_name_plural": "커뮤니티 게시글 이미지",
                "db_table": "community_post_image",
            },
        ),
    ]
