# Generated by Django 5.2.1 on 2025-06-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_profile", "0001_initial"),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_reads",
                        to="community_profile.communityprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 읽음 기록",
                "verbose_name_plural": "게시글 읽음 기록",
                "db_table": "post_read",
                "unique_together": {("post", "user_profile")},
            },
        ),
    ]
