# Generated by Django 5.2 on 2025-05-12 04:22

import auth.user.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "nickname",
                    models.CharField(
                        default=auth.user.models.random_nickname_generator,
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("profile_image", models.URLField(null=True)),
                (
                    "default_color",
                    models.CharField(
                        default=auth.user.models.random_color_generator, max_length=7
                    ),
                ),
                (
                    "introduction",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_withdrawn", models.BooleanField(default=False)),
                (
                    "naver_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "kakao_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "route",
                    models.IntegerField(
                        choices=[(0, "캐치비"), (1, "네이버"), (2, "카카오")], default=0
                    ),
                ),
                ("notification_agreed", models.BooleanField(default=False)),
                ("notification_agreed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="person.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "회원",
                "verbose_name_plural": "회원",
                "db_table": "user",
            },
        ),
    ]
